name: Build Latest Docker

on:
  push:
    branches:
      - main
    paths:
      - "**/*.js"
      - "**/*.ts"
      - "**/*.json"
      - yarn.lock
      - Dockerfile
      - .github/workflows/main.yml
  schedule:
    - cron: 0 1 * * 1

concurrency:
  group: ci-tests-${{ github.ref }}-main
  cancel-in-progress: true

jobs:
  main:
    name: Build Main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Docker meta
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: ghcr.io/${{ github.actor }}/devtool
          flavor: latest=true
          tags: |
            type=sha
            type=sha,format=long

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha,mode=max,scope=main
          cache-to: type=gha,mode=max,scope=main

  helper:
    name: Build Helper
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Docker meta
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: ghcr.io/${{ github.actor }}/devtool-helper
          flavor: latest=true
          tags: |
            type=sha
            type=sha,format=long

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.helper
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha,mode=max,scope=helper
          cache-to: type=gha,mode=max,scope=helper

  deploy:
    name: Deploy
    if: github.event_name == 'push'
    needs:
      - main
      - helper
    runs-on: ubuntu-latest
    steps:
      - name: Rollout
        uses: appleboy/ssh-action@master
        env:
          MAIN: ghcr.io/${{ github.actor }}/devtool:sha-${{ github.sha }}
          HELPER: ghcr.io/${{ github.actor }}/devtool-helper:sha-${{ github.sha }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SECRET_KEY }}
          envs: MAIN,HELPER
          script: kubectl set image deployment/devtool devtool=$MAIN helper=$HELPER
