name: Build Nightly Docker

on:
  push:
    branches:
      - feat/helper
  workflow_dispatch:

concurrency:
  group: ci-tests-${{ github.ref }}-nightly
  cancel-in-progress: true

jobs:
  main:
    name: Build Main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Generate Docker meta
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: ghcr.io/${{ github.actor }}/devtool
          flavor: latest=false
          tags: |
            type=sha
            type=sha,format=long
            nightly

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  helper:
    name: Build Helper
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Generate Docker meta
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: ghcr.io/${{ github.actor }}/devtool-helper
          flavor: latest=false
          tags: |
            type=sha
            type=sha,format=long
            nightly

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.helper
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
