name: CI

on:
  push:
    branches-ignore:
      - dependabot/**
    paths-ignore:
      - README.md
      - LICENSE
      - nodemon.json
      - Dockerfile
      - .dockerignore
      - .editorconfig
      - .gitignore
  pull_request_target:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip]')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install Node v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Run ESLint
        run: yarn eslint
